// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace LinqLanguageEditor2022
{
    internal sealed partial class Vsix
    {
        public const string Id = "LinqLanguageEditor2022.BF208545-2FC0-4EAD-8A40-127D737B9793";
        public const string Name = "LinqLanguageEditor2022";
        public const string Description = @"Linq Language Editor for Visual Studio 2022";
        public const string Language = "en-US";
        public const string Version = "1.9";
        public const string Author = "Danny McNaught";
        public const string Tags = "LINQ, Editor, ToolWindow";
    }
}
