// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace LinqLanguageEditor2022
{
    internal sealed partial class Vsix
    {
        public const string Id = "LinqLanguageEditor2022.acbb8393-6756-4c43-acca-e353cc952b47";
        public const string Name = "LinqLanguageEditor2022";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Danny McNaught";
        public const string Tags = "";
    }
}
