// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace LinqLanguageEditor2022
{
    internal sealed partial class Vsix
    {
        public const string Id = "LinqLanguageEditor2022.4f8f00b3-092c-4ae1-8d8b-40071b95069d";
        public const string Name = "LinqLanguageEditor2022";
        public const string Description = @"Linq Language Editor for Visual Studio 2022";
        public const string Language = "en-US";
        public const string Version = "1.5";
        public const string Author = "Danny McNaught";
        public const string Tags = "";
    }
}
