// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace LinqLanguageEditor2022
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string LinqEditorFactoryString = "0ca07535-1a01-485d-9e65-59b7384a593c";
        public static Guid LinqEditorFactory = new Guid(LinqEditorFactoryString);

        public const string LinqLanguageEditor2022String = "41af2c63-3a01-41dc-b52f-fca23fe50f01";
        public static Guid LinqLanguageEditor2022 = new Guid(LinqLanguageEditor2022String);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int LinqToolWindowCommand = 0x0100;
        public const int LinqTWindowToolbar = 0x1000;
        public const int LinqTWindowToolbarGroup = 0x1050;
        public const int DisplayLinqPadMethodResults = 0x0112;
        public const int LinqEditorGroup = 0x0001;
    }
}
