// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace LinqLanguageEditor2022
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string LinqEditorFactoryString = "b09b2281-c414-4773-961f-f5b613c49ef3";
        public static Guid LinqEditorFactory = new Guid(LinqEditorFactoryString);

        public const string LinqLanguageEditor2022String = "572acd30-b221-4944-90f2-d763bcfbc8ab";
        public static Guid LinqLanguageEditor2022 = new Guid(LinqLanguageEditor2022String);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int LinqCommand = 0x0100;
        public const int LinqTWindowToolbar = 0x1000;
        public const int LinqTWindowToolbarGroup = 0x1050;
        public const int DisplayLinqPadStatementsResults = 0x0111;
        public const int DisplayLinqPadMethodResults = 0x0112;
        public const int LinqEditorLinqPad = 0x0114;
        public const int LinqEditorGroup = 0x0001;
    }
}
